### ISSUE TITLE
Incompatible with 4.7.0 / Method getExtensions available in 4.7.13

### ISSUE THREAD

**Issue by alexschwarz89** [OXIDprojects/metadataGenerator#10]
The function `getExtensions` in `oxModule` is introduced in 4.7.13, but readme says compatible in 4.7.x, so there is a fatal error. 

```
public function getExtensions()
  {
        return isset( $this->_aModule['extend'] ) ? $this->_aModule['extend'] : array();
  }
```

**Comment by kermie** [comment]
@alexschwarz89 can you send a pull request to resolve this issue?
